# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 10:09
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20151202_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
